/**
 * Mock Task Data
 * 
 * Feature: 001-tasks-page-design
 * 25-30 diverse tasks for development and testing
 * Covers all statuses, priorities, and various conditions
 */

import type { Task, User } from '../types/task.types'

// Sample users
const users: Record<string, User> = {
    alice: { id: 1, name: 'Alice Johnson', avatar: 'https://i.pravatar.cc/150?img=1' },
    bob: { id: 2, name: 'Bob Smith', avatar: 'https://i.pravatar.cc/150?img=2' },
    carol: { id: 3, name: 'Carol Davis', avatar: 'https://i.pravatar.cc/150?img=3' },
    dave: { id: 4, name: 'Dave Wilson', avatar: 'https://i.pravatar.cc/150?img=4' },
    eve: { id: 5, name: 'Eve Martinez', avatar: 'https://i.pravatar.cc/150?img=5' },
    frank: { id: 6, name: 'Frank Garcia', avatar: null },
    grace: { id: 7, name: 'Grace Lee', avatar: 'https://i.pravatar.cc/150?img=7' },
    henry: { id: 8, name: 'Henry Brown', avatar: 'https://i.pravatar.cc/150?img=8' },
}

const creator = users.alice

/**
 * Generate mock task data
 * Returns 28 diverse tasks covering all statuses, priorities, and conditions
 */
export function getMockTasks(): Task[] {

    return [
        // TODO: 8 tasks
        {
            id: 1,
            title: 'Design new dashboard layout',
            description: 'Create wireframes and mockups for the analytics dashboard redesign project',
            status: 'TODO',
            priority: 'HIGH',
            dueDate: '2026-03-15',
            assignee: users.bob,
            creator,
            createdAt: '2026-02-15T10:00:00Z',
            updatedAt: '2026-02-26T08:30:00Z',
            tags: ['design', 'ui'],
            department: 'Design',
            relatedDocumentsCount: 3,
        },
        {
            id: 2,
            title: 'Review Q1 budget proposal',
            description: 'Review and approve the quarterly budget allocation for all departments',
            status: 'TODO',
            priority: 'URGENT',
            dueDate: '2026-02-28',
            assignee: users.carol,
            creator,
            createdAt: '2026-02-20T14:00:00Z',
            updatedAt: '2026-02-26T09:15:00Z',
            tags: ['finance', 'approval'],
            department: 'Finance',
            relatedDocumentsCount: 5,
        },
        {
            id: 3,
            title: 'Update user documentation',
            description: 'Add new sections covering the recently added features',
            status: 'TODO',
            priority: 'MEDIUM',
            dueDate: '2026-03-10',
            assignee: users.dave,
            creator,
            createdAt: '2026-02-18T11:00:00Z',
            updatedAt: '2026-02-25T16:45:00Z',
            tags: ['documentation', 'writing'],
            department: 'Technical Writing',
            relatedDocumentsCount: 2,
        },
        {
            id: 4,
            title: 'Schedule team meeting',
            description: 'Organize quarterly planning meeting for the engineering team',
            status: 'TODO',
            priority: 'LOW',
            dueDate: '2026-03-05',
            assignee: null,
            creator,
            createdAt: '2026-02-22T09:30:00Z',
            updatedAt: '2026-02-26T10:00:00Z',
            tags: ['meeting'],
            department: 'Engineering',
            relatedDocumentsCount: 0,
        },
        {
            id: 5,
            title: 'Refactor payment module',
            description: 'Clean up legacy code and improve type safety in payment processing',
            status: 'TODO',
            priority: 'HIGH',
            dueDate: '2026-03-20',
            assignee: users.henry,
            creator,
            createdAt: '2026-02-16T08:00:00Z',
            updatedAt: '2026-02-24T14:20:00Z',
            tags: ['refactor', 'code-quality'],
            department: 'Engineering',
            relatedDocumentsCount: 1,
        },
        {
            id: 6,
            title: 'Create marketing calendar for Q2',
            description: 'Plan and schedule social media posts and marketing campaigns',
            status: 'TODO',
            priority: 'MEDIUM',
            dueDate: '2026-03-08',
            assignee: users.eve,
            creator,
            createdAt: '2026-02-19T13:00:00Z',
            updatedAt: '2026-02-25T11:30:00Z',
            tags: ['marketing', 'calendar'],
            department: 'Marketing',
            relatedDocumentsCount: 4,
        },
        {
            id: 7,
            title: 'Conduct performance review',
            description: 'Complete annual performance review for team members',
            status: 'TODO',
            priority: 'HIGH',
            dueDate: '2026-03-01',
            assignee: users.grace,
            creator,
            createdAt: '2026-02-17T10:00:00Z',
            updatedAt: '2026-02-26T09:45:00Z',
            tags: ['hr', 'performance'],
            department: 'Human Resources',
            relatedDocumentsCount: 2,
        },
        {
            id: 8,
            title: 'Investigate database performance issue',
            description: null,
            status: 'TODO',
            priority: 'URGENT',
            dueDate: '2026-02-27',
            assignee: users.frank,
            creator,
            createdAt: '2026-02-26T07:00:00Z',
            updatedAt: '2026-02-26T15:30:00Z',
            tags: ['database', 'devops'],
            department: 'DevOps',
            relatedDocumentsCount: 0,
        },
        // IN_PROGRESS: 10 tasks
        {
            id: 9,
            title: 'Implement new authentication system',
            description: 'Build OAuth 2.0 integration with multiple providers including Google, GitHub, and Azure AD',
            status: 'IN_PROGRESS',
            priority: 'HIGH',
            dueDate: '2026-03-10',
            assignee: users.henry,
            creator,
            createdAt: '2026-02-10T09:00:00Z',
            updatedAt: '2026-02-26T16:00:00Z',
            tags: ['auth', 'security'],
            department: 'Engineering',
            relatedDocumentsCount: 6,
        },
        {
            id: 10,
            title: 'Design new feature mockups',
            description: 'Create Figma mockups for the advanced filtering and reporting features',
            status: 'IN_PROGRESS',
            priority: 'MEDIUM',
            dueDate: '2026-03-12',
            assignee: users.alice,
            creator,
            createdAt: '2026-02-12T10:30:00Z',
            updatedAt: '2026-02-26T14:15:00Z',
            tags: ['design', 'ui', 'mockup'],
            department: 'Design',
            relatedDocumentsCount: 3,
        },
        {
            id: 11,
            title: 'Write unit tests for API endpoints',
            description: 'Achieve 90% code coverage for the REST API endpoints',
            status: 'IN_PROGRESS',
            priority: 'HIGH',
            dueDate: '2026-03-05',
            assignee: users.bob,
            creator,
            createdAt: '2026-02-18T08:00:00Z',
            updatedAt: '2026-02-26T15:45:00Z',
            tags: ['testing', 'qa'],
            department: 'QA',
            relatedDocumentsCount: 2,
        },
        {
            id: 12,
            title: 'Review and approve pull requests',
            description: 'Code review for pending PRs from the engineering team',
            status: 'IN_PROGRESS',
            priority: 'MEDIUM',
            dueDate: '2026-02-28',
            assignee: users.frank,
            creator,
            createdAt: '2026-02-24T11:00:00Z',
            updatedAt: '2026-02-26T13:20:00Z',
            tags: ['code-review'],
            department: 'Engineering',
            relatedDocumentsCount: 0,
        },
        {
            id: 13,
            title: 'Update API documentation',
            description: 'Document new endpoints and update OpenAPI specification',
            status: 'IN_PROGRESS',
            priority: 'LOW',
            dueDate: '2026-03-08',
            assignee: users.dave,
            creator,
            createdAt: '2026-02-20T14:00:00Z',
            updatedAt: '2026-02-26T10:30:00Z',
            tags: ['documentation', 'api'],
            department: 'Technical Writing',
            relatedDocumentsCount: 1,
        },
        {
            id: 14,
            title: 'Prepare sales presentations',
            description: 'Create presentation decks for upcoming client demonstrations',
            status: 'IN_PROGRESS',
            priority: 'HIGH',
            dueDate: '2026-03-02',
            assignee: users.eve,
            creator,
            createdAt: '2026-02-21T09:00:00Z',
            updatedAt: '2026-02-26T11:15:00Z',
            tags: ['sales', 'presentation'],
            department: 'Sales',
            relatedDocumentsCount: 7,
        },
        {
            id: 15,
            title: 'Infrastructure upgrade planning',
            description: 'Plan database migration and server capacity upgrades',
            status: 'IN_PROGRESS',
            priority: 'MEDIUM',
            dueDate: '2026-03-15',
            assignee: users.frank,
            creator,
            createdAt: '2026-02-14T13:00:00Z',
            updatedAt: '2026-02-26T12:45:00Z',
            tags: ['infrastructure', 'devops'],
            department: 'DevOps',
            relatedDocumentsCount: 4,
        },
        {
            id: 16,
            title: 'Customer feedback analysis',
            description: 'Analyze and categorize feedback from recent user surveys and interviews',
            status: 'IN_PROGRESS',
            priority: 'MEDIUM',
            dueDate: '2026-03-03',
            assignee: users.grace,
            creator,
            createdAt: '2026-02-19T10:00:00Z',
            updatedAt: '2026-02-26T09:00:00Z',
            tags: ['research', 'ux'],
            department: 'Product',
            relatedDocumentsCount: 3,
        },
        {
            id: 17,
            title: 'Employee training program setup',
            description: 'Organize and schedule training sessions for new software and processes',
            status: 'IN_PROGRESS',
            priority: 'LOW',
            dueDate: '2026-03-12',
            assignee: users.carol,
            creator,
            createdAt: '2026-02-22T15:00:00Z',
            updatedAt: '2026-02-26T14:30:00Z',
            tags: ['training', 'hr'],
            department: 'Human Resources',
            relatedDocumentsCount: 5,
        },
        {
            id: 18,
            title: 'Optimize database queries',
            description: 'Profile and optimize slow-running queries to improve performance',
            status: 'IN_PROGRESS',
            priority: 'HIGH',
            dueDate: '2026-03-01',
            assignee: users.henry,
            creator,
            createdAt: '2026-02-16T11:00:00Z',
            updatedAt: '2026-02-26T16:20:00Z',
            tags: ['performance', 'database'],
            department: 'Engineering',
            relatedDocumentsCount: 2,
        },
        // COMPLETED: 6 tasks
        {
            id: 19,
            title: 'Deploy v2.0 release',
            description: 'Release new version to production with all approved features',
            status: 'COMPLETED',
            priority: 'URGENT',
            dueDate: '2026-02-20',
            assignee: users.frank,
            creator,
            createdAt: '2026-02-01T08:00:00Z',
            updatedAt: '2026-02-20T17:00:00Z',
            tags: ['release', 'deployment'],
            department: 'DevOps',
            relatedDocumentsCount: 8,
        },
        {
            id: 20,
            title: 'Fix login page styling issues',
            description: 'Resolve CSS issues on login form for mobile devices',
            status: 'COMPLETED',
            priority: 'HIGH',
            dueDate: '2026-02-19',
            assignee: users.bob,
            creator,
            createdAt: '2026-02-17T10:00:00Z',
            updatedAt: '2026-02-19T15:30:00Z',
            tags: ['bugfix', 'frontend'],
            department: 'Engineering',
            relatedDocumentsCount: 1,
        },
        {
            id: 21,
            title: 'Finalize contract with vendor',
            description: 'Negotiate terms and finalize contract documentation',
            status: 'COMPLETED',
            priority: 'HIGH',
            dueDate: '2026-02-18',
            assignee: users.carol,
            creator,
            createdAt: '2026-02-10T09:00:00Z',
            updatedAt: '2026-02-18T11:45:00Z',
            tags: ['contracts', 'vendor'],
            department: 'Procurement',
            relatedDocumentsCount: 4,
        },
        {
            id: 22,
            title: 'Generate monthly reports',
            description: 'Create financial and operational reports for February',
            status: 'COMPLETED',
            priority: 'MEDIUM',
            dueDate: '2026-02-25',
            assignee: users.eve,
            creator,
            createdAt: '2026-02-20T13:00:00Z',
            updatedAt: '2026-02-25T16:00:00Z',
            tags: ['reporting', 'analytics'],
            department: 'Finance',
            relatedDocumentsCount: 3,
        },
        {
            id: 23,
            title: 'Conduct security audit',
            description: 'Third-party security audit and penetration testing',
            status: 'COMPLETED',
            priority: 'HIGH',
            dueDate: '2026-02-22',
            assignee: users.henry,
            creator,
            createdAt: '2026-02-08T10:00:00Z',
            updatedAt: '2026-02-22T14:20:00Z',
            tags: ['security', 'compliance'],
            department: 'Security',
            relatedDocumentsCount: 6,
        },
        {
            id: 24,
            title: 'Customer onboarding training',
            description: 'Complete onboarding training session with new enterprise client',
            status: 'COMPLETED',
            priority: 'MEDIUM',
            dueDate: '2026-02-21',
            assignee: users.grace,
            creator,
            createdAt: '2026-02-13T11:00:00Z',
            updatedAt: '2026-02-21T17:30:00Z',
            tags: ['training', 'customer'],
            department: 'Professional Services',
            relatedDocumentsCount: 5,
        },
        // BLOCKED: 4 tasks
        {
            id: 25,
            title: 'Mobile application development',
            description: 'Build mobile app for iOS and Android platforms (waiting on design approval)',
            status: 'BLOCKED',
            priority: 'HIGH',
            dueDate: '2026-04-01',
            assignee: users.alice,
            creator,
            createdAt: '2026-02-01T09:00:00Z',
            updatedAt: '2026-02-26T10:00:00Z',
            tags: ['mobile', 'development'],
            department: 'Engineering',
            relatedDocumentsCount: 7,
        },
        {
            id: 26,
            title: 'Enterprise integration',
            description: 'Integrate with enterprise resource planning system (waiting on API access)',
            status: 'BLOCKED',
            priority: 'URGENT',
            dueDate: '2026-03-20',
            assignee: users.henry,
            creator,
            createdAt: '2026-02-05T10:00:00Z',
            updatedAt: '2026-02-26T11:30:00Z',
            tags: ['integration', 'api'],
            department: 'Engineering',
            relatedDocumentsCount: 3,
        },
        {
            id: 27,
            title: 'Data migration project',
            description: 'Migrate customer data from legacy system (pending budget approval)',
            status: 'BLOCKED',
            priority: 'MEDIUM',
            dueDate: '2026-03-30',
            assignee: users.frank,
            creator,
            createdAt: '2026-02-12T14:00:00Z',
            updatedAt: '2026-02-26T12:15:00Z',
            tags: ['migration', 'data'],
            department: 'DevOps',
            relatedDocumentsCount: 2,
        },
        {
            id: 28,
            title: 'Client legal review',
            description: 'Obtain legal review of terms of service updates (with external counsel)',
            status: 'BLOCKED',
            priority: 'HIGH',
            dueDate: '2026-03-10',
            assignee: users.carol,
            creator,
            createdAt: '2026-02-18T09:00:00Z',
            updatedAt: '2026-02-26T13:45:00Z',
            tags: ['legal', 'compliance'],
            department: 'Legal',
            relatedDocumentsCount: 4,
        },
    ]
}
