/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantRegisterRouteImport } from './routes/$tenant/register'
import { Route as TenantLoginRouteImport } from './routes/$tenant/login'
import { Route as TenantDashboardRouteImport } from './routes/$tenant/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRegisterRoute = TenantRegisterRouteImport.update({
  id: '/$tenant/register',
  path: '/$tenant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/$tenant/login',
  path: '/$tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/$tenant/dashboard',
  path: '/$tenant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/register': typeof TenantRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/register': typeof TenantRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/register': typeof TenantRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$tenant/dashboard' | '/$tenant/login' | '/$tenant/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$tenant/dashboard' | '/$tenant/login' | '/$tenant/register'
  id:
    | '__root__'
    | '/'
    | '/$tenant/dashboard'
    | '/$tenant/login'
    | '/$tenant/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantLoginRoute: typeof TenantLoginRoute
  TenantRegisterRoute: typeof TenantRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/register': {
      id: '/$tenant/register'
      path: '/$tenant/register'
      fullPath: '/$tenant/register'
      preLoaderRoute: typeof TenantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/login': {
      id: '/$tenant/login'
      path: '/$tenant/login'
      fullPath: '/$tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/dashboard': {
      id: '/$tenant/dashboard'
      path: '/$tenant/dashboard'
      fullPath: '/$tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantLoginRoute: TenantLoginRoute,
  TenantRegisterRoute: TenantRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
