/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantRouteRouteImport } from './routes/$tenant/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TenantIndexRouteImport } from './routes/$tenant/index'
import { Route as TenantProfileRouteImport } from './routes/$tenant/profile'
import { Route as TenantRegisterRouteImport } from './routes/$tenant/register'
import { Route as TenantTasksRouteImport } from './routes/$tenant/tasks'
import { Route as TenantDocumentSharesIndexRouteImport } from './routes/$tenant/document-shares/index'
import { Route as TenantDocumentsIndexRouteImport } from './routes/$tenant/documents/index'
import { Route as TenantDocumentsIdRouteImport } from './routes/$tenant/documents/$id'
import { Route as TenantFavoritesIndexRouteImport } from './routes/$tenant/favorites/index'
import { Route as TenantPinnedDocumentsIndexRouteImport } from './routes/$tenant/pinned-documents/index'
import { Route as TenantTasksIndexRouteImport } from './routes/$tenant/tasks/index'
import { Route as TenantTeamsIndexRouteImport } from './routes/$tenant/teams/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRouteRoute = TenantRouteRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantProfileRoute = TenantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantRegisterRoute = TenantRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantTasksRoute = TenantTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantDocumentSharesIndexRoute =
  TenantDocumentSharesIndexRouteImport.update({
    id: '/document-shares/',
    path: '/document-shares/',
    getParentRoute: () => TenantRouteRoute,
  } as any)
const TenantDocumentsIndexRoute = TenantDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantDocumentsIdRoute = TenantDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantFavoritesIndexRoute = TenantFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantPinnedDocumentsIndexRoute =
  TenantPinnedDocumentsIndexRouteImport.update({
    id: '/pinned-documents/',
    path: '/pinned-documents/',
    getParentRoute: () => TenantRouteRoute,
  } as any)
const TenantTasksIndexRoute = TenantTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantTasksRoute,
} as any)
const TenantTeamsIndexRoute = TenantTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => TenantRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/$tenant/profile': typeof TenantProfileRoute
  '/$tenant/register': typeof TenantRegisterRoute
  '/$tenant/tasks': typeof TenantTasksRouteWithChildren
  '/$tenant/': typeof TenantIndexRoute
  '/$tenant/documents/$id': typeof TenantDocumentsIdRoute
  '/$tenant/document-shares/': typeof TenantDocumentSharesIndexRoute
  '/$tenant/documents/': typeof TenantDocumentsIndexRoute
  '/$tenant/favorites/': typeof TenantFavoritesIndexRoute
  '/$tenant/pinned-documents/': typeof TenantPinnedDocumentsIndexRoute
  '/$tenant/tasks/': typeof TenantTasksIndexRoute
  '/$tenant/teams/': typeof TenantTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$tenant/profile': typeof TenantProfileRoute
  '/$tenant/register': typeof TenantRegisterRoute
  '/$tenant': typeof TenantIndexRoute
  '/$tenant/documents/$id': typeof TenantDocumentsIdRoute
  '/$tenant/document-shares': typeof TenantDocumentSharesIndexRoute
  '/$tenant/documents': typeof TenantDocumentsIndexRoute
  '/$tenant/favorites': typeof TenantFavoritesIndexRoute
  '/$tenant/pinned-documents': typeof TenantPinnedDocumentsIndexRoute
  '/$tenant/tasks': typeof TenantTasksIndexRoute
  '/$tenant/teams': typeof TenantTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/$tenant/profile': typeof TenantProfileRoute
  '/$tenant/register': typeof TenantRegisterRoute
  '/$tenant/tasks': typeof TenantTasksRouteWithChildren
  '/$tenant/': typeof TenantIndexRoute
  '/$tenant/documents/$id': typeof TenantDocumentsIdRoute
  '/$tenant/document-shares/': typeof TenantDocumentSharesIndexRoute
  '/$tenant/documents/': typeof TenantDocumentsIndexRoute
  '/$tenant/favorites/': typeof TenantFavoritesIndexRoute
  '/$tenant/pinned-documents/': typeof TenantPinnedDocumentsIndexRoute
  '/$tenant/tasks/': typeof TenantTasksIndexRoute
  '/$tenant/teams/': typeof TenantTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/login'
    | '/$tenant/profile'
    | '/$tenant/register'
    | '/$tenant/tasks'
    | '/$tenant/'
    | '/$tenant/documents/$id'
    | '/$tenant/document-shares/'
    | '/$tenant/documents/'
    | '/$tenant/favorites/'
    | '/$tenant/pinned-documents/'
    | '/$tenant/tasks/'
    | '/$tenant/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$tenant/profile'
    | '/$tenant/register'
    | '/$tenant'
    | '/$tenant/documents/$id'
    | '/$tenant/document-shares'
    | '/$tenant/documents'
    | '/$tenant/favorites'
    | '/$tenant/pinned-documents'
    | '/$tenant/tasks'
    | '/$tenant/teams'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/login'
    | '/$tenant/profile'
    | '/$tenant/register'
    | '/$tenant/tasks'
    | '/$tenant/'
    | '/$tenant/documents/$id'
    | '/$tenant/document-shares/'
    | '/$tenant/documents/'
    | '/$tenant/favorites/'
    | '/$tenant/pinned-documents/'
    | '/$tenant/tasks/'
    | '/$tenant/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRouteRoute: typeof TenantRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/profile': {
      id: '/$tenant/profile'
      path: '/profile'
      fullPath: '/$tenant/profile'
      preLoaderRoute: typeof TenantProfileRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/register': {
      id: '/$tenant/register'
      path: '/register'
      fullPath: '/$tenant/register'
      preLoaderRoute: typeof TenantRegisterRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/tasks': {
      id: '/$tenant/tasks'
      path: '/tasks'
      fullPath: '/$tenant/tasks'
      preLoaderRoute: typeof TenantTasksRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/document-shares/': {
      id: '/$tenant/document-shares/'
      path: '/document-shares'
      fullPath: '/$tenant/document-shares/'
      preLoaderRoute: typeof TenantDocumentSharesIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/documents/': {
      id: '/$tenant/documents/'
      path: '/documents'
      fullPath: '/$tenant/documents/'
      preLoaderRoute: typeof TenantDocumentsIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/documents/$id': {
      id: '/$tenant/documents/$id'
      path: '/documents/$id'
      fullPath: '/$tenant/documents/$id'
      preLoaderRoute: typeof TenantDocumentsIdRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/favorites/': {
      id: '/$tenant/favorites/'
      path: '/favorites'
      fullPath: '/$tenant/favorites/'
      preLoaderRoute: typeof TenantFavoritesIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/pinned-documents/': {
      id: '/$tenant/pinned-documents/'
      path: '/pinned-documents'
      fullPath: '/$tenant/pinned-documents/'
      preLoaderRoute: typeof TenantPinnedDocumentsIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/tasks/': {
      id: '/$tenant/tasks/'
      path: '/'
      fullPath: '/$tenant/tasks/'
      preLoaderRoute: typeof TenantTasksIndexRouteImport
      parentRoute: typeof TenantTasksRoute
    }
    '/$tenant/teams/': {
      id: '/$tenant/teams/'
      path: '/teams'
      fullPath: '/$tenant/teams/'
      preLoaderRoute: typeof TenantTeamsIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
  }
}

interface TenantTasksRouteChildren {
  TenantTasksIndexRoute: typeof TenantTasksIndexRoute
}

const TenantTasksRouteChildren: TenantTasksRouteChildren = {
  TenantTasksIndexRoute: TenantTasksIndexRoute,
}

const TenantTasksRouteWithChildren = TenantTasksRoute._addFileChildren(
  TenantTasksRouteChildren,
)

interface TenantRouteRouteChildren {
  TenantProfileRoute: typeof TenantProfileRoute
  TenantRegisterRoute: typeof TenantRegisterRoute
  TenantTasksRoute: typeof TenantTasksRouteWithChildren
  TenantIndexRoute: typeof TenantIndexRoute
  TenantDocumentsIdRoute: typeof TenantDocumentsIdRoute
  TenantDocumentSharesIndexRoute: typeof TenantDocumentSharesIndexRoute
  TenantDocumentsIndexRoute: typeof TenantDocumentsIndexRoute
  TenantFavoritesIndexRoute: typeof TenantFavoritesIndexRoute
  TenantPinnedDocumentsIndexRoute: typeof TenantPinnedDocumentsIndexRoute
  TenantTeamsIndexRoute: typeof TenantTeamsIndexRoute
}

const TenantRouteRouteChildren: TenantRouteRouteChildren = {
  TenantProfileRoute: TenantProfileRoute,
  TenantRegisterRoute: TenantRegisterRoute,
  TenantTasksRoute: TenantTasksRouteWithChildren,
  TenantIndexRoute: TenantIndexRoute,
  TenantDocumentsIdRoute: TenantDocumentsIdRoute,
  TenantDocumentSharesIndexRoute: TenantDocumentSharesIndexRoute,
  TenantDocumentsIndexRoute: TenantDocumentsIndexRoute,
  TenantFavoritesIndexRoute: TenantFavoritesIndexRoute,
  TenantPinnedDocumentsIndexRoute: TenantPinnedDocumentsIndexRoute,
  TenantTeamsIndexRoute: TenantTeamsIndexRoute,
}

const TenantRouteRouteWithChildren = TenantRouteRoute._addFileChildren(
  TenantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRouteRoute: TenantRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
